apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          # image: registry.cn-hongkong.aliyuncs.com/h8rdev/devbox
          image: busybox
          command: ["sh", "-c"]
          args:
            - tail -f /dev/null
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090